Add music player keybindings
DamienCassou/desktop-environment pull request #12
Opened 2020-11-11 01:28 UTC by Duarte-Dias

I have media keys on my laptop and decided to implement their functionality. I used [playerctl](https://github.com/altdesktop/playerctl) since it is simple and seems to be available on a lot of systems.

2020-11-12 09:03 UTC, DamienCassou requested changes
Excellent job. I left a few comments that I would like you to take into consideration. When you are done, please squash all your commits into 1.

2020-11-12 09:03 UTC, DamienCassou commented on desktop-environment.el
> +           (,(kbd "<XF86AudioPlay>") . ,(function desktop-environment-toggle-music))
can you please add a "Music controls" comment to separate the new lines?

2020-11-12 09:04 UTC, DamienCassou commented
Thank you very much for your work!

2020-11-12 18:32 UTC, Duarte-Dias commented
I made the changes you suggested.
I'm leaving the commits unsquashed so that you can see the latest changes, I believe you can merge with the squashing option. If you can't just ping me again and I will squash.

2020-11-17 16:56 UTC, DamienCassou commented
I squashed your commits and merged into `master`. Thank you for your work!

2020-11-17 16:56 UTC, closed without merging