Added stop for music player instance
DamienCassou/desktop-environment pull request #21
Opened 2021-01-27 04:27 UTC by maxminoS

Also bound the stop button to the stop media key

2021-01-28 19:11 UTC, DamienCassou requested changes
Excellent. Would you mind adding the necessary key bindings to the README please?

2021-01-28 19:11 UTC, DamienCassou commented on desktop-environment.el
> +(defun desktop-environment-music-stop()
can you please add a space before the list of arguments?

2021-01-29 03:55 UTC, maxminoS commented
Sure!

I have added the relevant keybindings into the README and fixed the function-argument spacing.

2021-01-29 06:58 UTC, DamienCassou approved these changes
This is perfect, thank you. Final step is to squash all your commits into just one.

2021-01-29 06:59 UTC, DamienCassou commented
Please also rebase on top of latest master, your branch is out-of-date.

2021-01-29 15:30 UTC, maxminoS commented
I think I've just successfully rebased it and will just need the review to merge it.

2021-01-29 16:09 UTC, DamienCassou requested changes
Please squash your 2 commits into just 1 please (you did a "merge" instead of a "rebase").

2021-01-29 20:15 UTC, maxminoS commented
Sorry for the mistake, I definitely checked the logs this time and made sure I rebased it correctly.

2021-01-29 20:17 UTC, DamienCassou approved these changes
Perfect! Thank you very much

2021-01-29 20:18 UTC, merged